### ISSUE TITLE
problem reading a mutt maildir as local folder

### ISSUE THREAD

**Issue by eric-blabla** [cleidigh/Localfolder-TB#57]
I try to read a mutt maildir. It is organized in the 3 subfolders "cur, new, tmp". Neither selecting the /basicpath/ of the folder nor selecting /basicpath/cur  as source dir  will show any mails  (yes, I did check maildir format). Using " mutt -f   /basicpath/ " works perfectly.

What am I missing? Thank you

**Comment by cleidigh** [comment]
@eric-blabla 
After a long hiatus for personal reasons, I am back and working on LocalFolders.

I have not done much with maildir since my qmail days. Right now I have to prioritize 102 support, however, if you can create a zip of a basic structure with a couple of fake emails, that will give me something to work with.
@cleidigh
