### ISSUE TITLE
Cannot use opened VeraCrypt partition

### ISSUE THREAD

**Issue by symonjim** [cleidigh/Localfolder-TB#65]
I'm hoping to save emails into my VeraCrypt encrypted drive partition. (No, the Thunderbird mail encryption scheme does not work for my purposes as far as I can tell). When mounted that partition behaves just like any other drive, writing reading and so on. When I create a LocalFolders Thunderbird folder on my C: drive it works fine. Messages get saved there as usual. When I create a LocalFolders Thunderbird folder on the VeraCrypt drive nothing shows up in that space when I try to save a mail message to that folder. The folder gets created and shows up in Thunderbird looking just like the one on the C: drive.

Any chance of making this work?

Thanks,

Jim

**Comment by symonjim** [comment]
Localfolders 3.3.2

**Comment by cleidigh** [comment]
@symonjim 
Can you id your os and tb versions also.
I have not had experience with encrypted drives with localfolders.
Like you said it should be transparent to the application. I will look at VeraCrypt, however, I am not in a position to install it soon as I would need a VM since I wouldn't install on my dev system.
Have you tried copying a single message into the folder?
@cleidigh

**Comment by cleidigh** [comment]
@symonjim 
Did you try copying a single message?  The fact that you indicated the folder structure was created means TB and IETNG were able to write to the drive.
Capture the console output when you try to do the copy.
@cleidigh
